### ISSUE TITLE
Ability to use Discord channel IDs

### ISSUE THREAD

**Issue by Spacelord09** [roydejong/timbot#36] opened 2021-09-26 15:00 UTC
It would be great to be able to use discord channel IDs instedt of names, due to changing channel names.

**Comment by camfsd** [comment] 2021-09-27 01:33
It's best practice to use channel IDs for these sort of things so I'm not too sure why an experienced developer (judging by his github profile) would have done it with this method.

The project appears to be quite neglected. You're better off finding an alternative.

**Comment by roydejong** [comment] 2021-09-27 10:06
Duplicate of #24. I agree it'd be nice to have the option to set IDs.

> It's best practice to use channel IDs for these sort of things so I'm not too sure why an experienced developer (judging by his github profile) would have done it with this method.
> 
> The project appears to be quite neglected. You're better off finding an alternative.

Ouch my feelings

This was a little "for fun" project that I decided to share, don't take it too seriously :)

Setting a channel name like "stream-announcements" was sufficient for most purposes - I think something can be said for either approach. Setting a name breaks the config if the channel is renamed. Setting an ID breaks the config if the channel is deleted. Probably, neither happen too often and the former is easier to explain and set up.

**Closed as completed by roydejong** 2021-09-27 10:06 UTC
