### ISSUE TITLE
Error in streams refresh: TypeError: fields.flat is not a function

### ISSUE THREAD

**Issue by YTNico71** [roydejong/timbot#28] opened 2021-06-04 12:38 UTC
`[StreamActivity] Update current activity: watching YTNico7171.
[TwitchMonitor] Error in streams refresh: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/ytnico7171/timbot-master/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/ytnico7171/timbot-master/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/ytnico7171/timbot-master/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at Function.createForStream (/home/ytnico7171/timbot-master/live-embed.js:29:16)
    at TwitchMonitor.onChannelLiveUpdate (/home/ytnico7171/timbot-master/index.js:492:32)
    at Function.handleChannelLiveUpdate (/home/ytnico7171/timbot-master/twitch-monitor.js:220:21)
    at Function.handleStreamList (/home/ytnico7171/timbot-master/twitch-monitor.js:182:23)
    at TwitchApi.fetchStreams.then (/home/ytnico7171/timbot-master/twitch-monitor.js:95:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

i need help please

**Comment by roydejong** [comment] 2021-06-04 12:38
Duplicate of #26.

> This most likely means you are using an older version of Node.js, try updating to v12.
> See: https://stackoverflow.com/a/61034427/1410310

**Closed as completed by roydejong** 2021-06-04 12:38 UTC
